version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_cost_optimizer
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
